### PR TITLE
Update ru translation

### PR DESCRIPTION
**Pull request by kt0t0Sudd3n**

### CODE REVIEW

**Comment by tripplehelix** [comment]
@kt0t0Sudd3n my beautiful husband. This is great and all... but what about https://github.com/DexterHuang/CyberCodeOnline/pull/681 as it would need merging first

**Comment by kt0t0Sudd3n** [comment]
@tripplehelix my love. #681 can be closed, but if not, it`s fine to merge that and this one too, ill pr some edits after

**Comment by tripplehelix** [comment]
@kt0t0Sudd3n I have done as asked my love

**Comment by kt0t0Sudd3n** [comment]
@tripplehelix love you <3

**Pull request merged**
