### PR TITLE
Update locations.md

### PR DESCRIPTION
**Pull request by Misaki290**
Rephrased almost the entire section of "Locations".
Moved the information about 3D Molecular Printer and Weaponsmith from Inventory to this section.
Added additional information on other locations.
Added 2 more locations that didn't existed initially.
Added pictures of every location.
(second commit)

### CODE REVIEW

**Comment by tripplehelix** [comment]
<3 Misaki! Will merge this, make sure the images aren't too big in game. If they are you may need to shrink them a bit.

**Comment by tripplehelix** [comment]
I will transfer the images to GitHub soon.

**Comment by Misaki290** [comment]
> I will transfer the images to GitHub soon.

The links needs to be replaced with the ones uploaded in the GitHUB, otherwise they don't show in-game despite showing up correctly here in GitHUB.

Thanks again, you're a sweetheart! 💗

**Comment by tripplehelix** [comment]
@Misaki290 your images didn't work, I don't think the site allows for offsite image hosting.

**Comment by Misaki290** [comment]
> @Misaki290 your images didn't work, I don't think the site allows for offsite image hosting.

I know. That's why after you upload them here, I will replace them. Or you can do that as well.

**Pull request merged**
