### PR TITLE
keys and frags added in this seperate page

### PR DESCRIPTION
**Pull request by Omnipotent-God**

### CODE REVIEW

**Comment by tripplehelix** [comment]
There are spelling issues here. Also let's put in some of the area names.

Flori > Kashi > Yamesa > Floranda > Akisarao

Maybe also explain that each sector is for a certain range of levels, when they unlock and what level you need to be to see them etc.

**Comment by Omnipotent-God** [comment]
done. i dont think that the area names are complete though i might need to ask dexter for all area names and order

**Comment by tripplehelix** [comment]
Nice, needs cleaning but we can do that once we have all information.

**Comment by DexterHuang** [comment]
hey like mentioned in discord, its better we don't show the names of the area, because it could change in future, to avoid confusion :)
I will close this one first, just open again when you made the change 👍

**Pull request closed without merging**
