### PR TITLE
Darkrevelations patch 1

### PR DESCRIPTION
**Pull request by darkrevelations**
Several changes. Lore additions, several dungeons. Word update will be in next patch.

### CODE REVIEW

**Comment by darkrevelations** [comment]
Files for lore are named according to their creators.

**Comment by darkrevelations** [comment]
Added lore from Satan.

**Comment by DexterHuang** [comment]
@darkrevelations amazing! but can we break some of the lore notes into smaller chunks? because the UI isn't very suitable for big long texts

**Comment by tripplehelix** [comment]
@darkrevelations remove the larger lore... but did you add all these files to the list? index.json

**Comment by tripplehelix** [comment]
@darkrevelations please accept all the PR's on your repo then add those files to this PR.

**Comment by tripplehelix** [comment]
@darkrevelations Also add all the names of the people that contributed to the credits.md in the root directory. Make sure to put two spaces after each name so it formats it correctly.

**Comment by darkrevelations** [comment]
All necessary changes are pushed. Apologies for the late response. I finally got some sleep.

**Comment by darkrevelations** [comment]
syntax fix. Minor change. Added two spaces I missed (had a feeling).

**Comment by tripplehelix** [comment]
And the index.json @darkrevelations I updated it on your master

**Comment by darkrevelations** [comment]
Was able to pull it up via your update that posted here but not to my patch branch. Odd that it didn't show up.

Also, in case you didn't see, I invited you as a contributor to my repo so that these things can be resolved if I'm not available.

**Comment by tripplehelix** [comment]
Was no. 4 deleted?

**Comment by darkrevelations** [comment]
Number 4 was renamed to Number 3.

**Comment by darkrevelations** [comment]
I see where the error was. You submitted 2, 3, and 4 to mine. You didn't submit 1 on my end, thus I thought 2, 3, and 4 were a split of 1 rather than 1 being a split of itself.

The error was corrected. 1 is now `NinkPT.md` instead of `NinkPT_1.md` to correct this matter.

**Pull request merged**
