### PR TITLE
Create HQ_LAC

### PR DESCRIPTION
**Pull request by JasonVanJason**

### CODE REVIEW

**Comment by DexterHuang** [comment]
hi, same thing I think you wanna add this to 
https://github.com/DexterHuang/CyberCodeOnline/blob/master/contribution/item/lore.json
instead :)
also try not to use player names too often, its more lore-friendly that way, unless your name sounds like a character from cyberpunk universe

**Comment by JasonVanJason** [comment]
Your moderator continue to abuse mute I said nothing offensive

**Comment by JasonVanJason** [comment]
Apparently unca Feddit thinks I am annoying and rude as well, these people
that represent you are way too strict

**Comment by DexterHuang** [comment]
@JasonVanJason  I just checked the log, seems like you were muted because of spamming? 
if you have question please do Dm me on discord :) we can talk there

**Comment by JasonVanJason** [comment]
No thank you, I will just change my reviews to 1 star now, I see no point
in participating somewhere I am not wanted.

**Comment by DexterHuang** [comment]
@JasonVanJason that is very unfortunate... to be fair I didn't do any wrong to you, would be very saddening for me if you revenge on me for your anger towards another person.

**Comment by JasonVanJason** [comment]
You are the developer, you have other players running wild with a function
you let them have, the idea that you are without culpability is ridiculous,
if it was a regular MMO you might be right but in a text based game the
chat is the sole reason people play, I place the blame squarely on your
shoulders.

**Comment by DexterHuang** [comment]
I understand, I am really sorry :(

**Comment by DexterHuang** [comment]
@JasonVanJason I understand, I am really sorry :( You have my sincerest appology.

**Comment by JasonVanJason** [comment]
If you were really sorry you would make a change to your oppressive
moderators but you will not change them, they are destroying your community
with their own ideals, I think you will be much more sorry when you watch
them drive more players away

**Comment by DexterHuang** [comment]
You are absolutely right, I will certainly take this seriously and have a meeting with them. thank you for shading light on the situation :)

**Comment by JasonVanJason** [comment]
They are volunteers, they feel they are doing you a favor, that meeting
will not go your way because they feel they are helping you, for you to
tell them otherwise, again, it is not going to go well for you, you just
need to replace them, plain and simple, I don't care, I've uninstalled, but
just know I've been a part of many development cycles involving volunteers
and this is constantly an issue, good luck, I won't be changing my reviews
but hopefully you can find some better people who understand that they are
effectively taking money out of your hands when they mute people because
they don't seem to understand that.

**Comment by JasonVanJason** [comment]
You are still relaxed about this because Google Play refunds have not
started yet, once the refunds start being requested you will see exactly
what I am talking about, if enough refunds are requested they just start
issuing refunds without any input from your end.

**Pull request closed without merging**
