### PR TITLE
Updated a few files

### PR DESCRIPTION
**Pull request by Datarata**
BA5ED5B9-55F9-4705-BF75-1596EF2A1399
**UPDATE 25.12.22**

>/contribution/lang/ru.json

• Changed "Dungeon" to "Metro" at the request of players, as it fits more with the mechanics of "Stations"
• Fixed "You" to "You" a bit more. For Russian speakers, these are two different words.
• Changed display errors of my previous translation
• Localized some texts
• Changed names of equipment parts to match the names of items
• Reduced some words to display correctly
• Edited previous translator's information

>/contribution/mobile/ru/tips.txt

• Removed repetitive (50%)
• Fixed syntax and spelling errors
• Translator tooltips changed
• Added new

>/contribution/mobile/ru/procedural-names.json

_Fixed the translation of some words, and tried to make the names read well for Russians:_

• Edited the instructions.
• Edited quality names.
• Added/deleted/changed names of weapons and equipment.

>/contribution/mobile/ru/dungeon-lore/Liam.md

• Added the story of how Liam became a netrunner

### CODE REVIEW

**Comment by DexterHuang** [comment]
hello, there seems to still be some conflicts, also please don't add mention of gang names

**Comment by Datarata** [comment]
> hello, there seems to still be some conflicts, also please don't add mention of gang names

Okay, I'll delete the gang names. I don't know how to fix the file and fix the conflict( I'd love your help...

**Comment by B3lli4l** [comment]
You can click "details" on the check error to see what it is. From what I can see, it is: "Error: ./contribution/mobile/ru/procedural-names.json is invalid JSON, SyntaxError: Unexpected string in JSON at position 1391", then I would start by heading to position 1391 in procedural-names.json and see. From the details, it may be a $path spelling error. Hope that helps.

**Comment by Datarata** [comment]
> You can click "details" on the check error to see what it is. From what I can see, it is: "Error: ./contribution/mobile/ru/procedural-names.json is invalid JSON, SyntaxError: Unexpected string in JSON at position 1391", then I would start by heading to position 1391 in procedural-names.json and see. From the details, it may be a $path spelling error. Hope that helps.

Thanks for the comment, but unfortunately there is only «"Chōshima",» on line 1391, and no syntax errors :(

I'm not good at JSON, but I think I understood you correctly...

**Pull request closed without merging**
