### PR TITLE
Update words.json- word bank clean up 

### PR DESCRIPTION
**Pull request by byakkozen**
removed a redundant dialogue line from weaponsmith 
removed a redundant enemy type "Karen"; there was 2 entries of "karen",
slight alteration of some enemy 
removed a redundant enemy type "wirehead", there was 2 entries of "wirehead"
Aims to alphabetize entries in each section so it's easier to see whats there already in the future (if it doesnt mess up the RNG generating in the game)
removed the redundant enemy type "master chief" since it shows up as both a enemy type and boss type

### CODE REVIEW

**Comment by tripplehelix** [comment]
Alphabetically ordering these lists doesn't work as people just add to the bottom of lines. It also makes it harder for Dex to spot JSON errors if items are added randomly. Great work cleaning it all up. We've had people try this before.

**Comment by byakkozen** [comment]
i have a master list now I saved seperately to myself I will just do regular upkeep

**Comment by tripplehelix** [comment]
Nice work! Now me, worzel and l33t are bad guys we are going to have to have a boss of ourselves 😂

**Comment by byakkozen** [comment]
hey no peeking

**Comment by byakkozen** [comment]
well i will leave that to the 3 putting the boss into words

**Comment by byakkozen** [comment]
like Worzel, The Warmaster
tripplehelix, The Tech Wiz
l33t4an3l, Queen of the Art Hive

**Comment by tripplehelix** [comment]
Oh my gosh, they are great!

**Comment by byakkozen** [comment]
would you perfer Tech Wiz tripplehelix or tripplehelix, The Tech Wiz?

**Comment by tripplehelix** [comment]
Keep em consistent. The way they are is great.

**Comment by byakkozen** [comment]
pushing commit now

**Comment by DexterHuang** [comment]
I think we might need to keep the self insert into a boss name to a minimum @@ especially the less lore-friendly ones, like smash potato lol but I will keep them for now :D lets have a cleanup in future

**Pull request merged**
