### PR TITLE
Update referral.jpg

### PR DESCRIPTION
**Pull request by turtwig**
Typo correction.

### CODE REVIEW

**Comment by DexterHuang** [comment]
what did you change?@@ you edited the image?

**Comment by turtwig** [comment]
I changed "conatiner" to "container"

I didn't fix any of the grammatical errors, but that typo was especially obvious every time I logged in.

**Comment by DexterHuang** [comment]
wow how did you do it? doesnt look like edited

**Comment by turtwig** [comment]
In Photoshop I cut the letters out, swapped them over and then blended the hard edges 👍

Glad you like it.

**Pull request merged**
