### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by kimileta**
Added new building words, cleaned up duplicates, fixed some typos, alphabetized lists to make it easier to tell if you're about to add duplicates

### CODE REVIEW

**Comment by DexterHuang** [comment]
hello i think the format of json is wrong @@ could you fix it?
also there is no need to reorder the json list, because I will have no idea what you have added haha

**Comment by kimileta** [comment]
I'm trying to figure out what happened to make it invalid json o_O

**Comment by DexterHuang** [comment]
oh hey @kimileta ! didnt realize its you!! haven't  seen you for a while :D

**Comment by kimileta** [comment]
yep I'm back!! :D

**Comment by DexterHuang** [comment]
I have fixed the syntax error for ya :D 
you could easily see whats the problem with JSON validator like https://jsonlint.com/

**Comment by kimileta** [comment]
oh okay! ill try not to break anything next time I send a PR :P

**Comment by DexterHuang** [comment]
haha dont worry it wont break anything :) there is automatic checks and unless I approved it, it wont affect anything ;)

**Pull request merged**
