### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by TeejayParker**
Added some greetings/needhelp, building types, goodguys, filler

### CODE REVIEW

**Comment by TeejayParker** [comment]
I'm not sure why this failed the json validation check, everything looks good, unless I'm just overlooking something.

**Comment by DexterHuang** [comment]
there is indeed an syntax error in words.json, try to copy the entire thing to some online JSON validator, it will show you exactly what is worng :)

**Comment by TeejayParker** [comment]
alright, I'll do that in just a bit and then update.

**Comment by TeejayParker** [comment]
JSON lint issues should be fixed.

**Pull request merged**
