### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by byronigoe**
Various spelling and grammar corrections.

### CODE REVIEW

**Review by Misaki290 — COMMENTED** [review]
I don't know about English grammar but in Romanian, if you use "or" or "and" you don't add a comma at the word that is preceded by the preposition "or" since you want to say "item 1 or item 2" and not "item 1 comma or item 2".
It can be either "item 1" OR "item 2".
There's no enumeration so you need to use comma, nor you need to make a pause (by using the comma) to highlight something.

**Comment by tripplehelix** [comment]
@Misaki290 I have merged this, feel free to remove those weird oxford commas

**Comment by byronigoe** [comment]
http://www.rosalindhartmann.com/wp-content/uploads/oxford-comma-meme.jpg

**Comment by Misaki290** [comment]
> @Misaki290 I have merged this, feel free to remove those weird oxford commas

What's the point, lol?

**Comment by byronigoe** [comment]
When there are more than 2 items in the list, you should add a comma after the penultimate item for clarity. E.g. tough, angry, or shielded

There was actually a court case that hinged on this serial, or so-called Oxford, comma. https://www.huffpost.com/entry/oxford-comma-court-case-ruling-overtime_n_58cad41ae4b0ec9d29d9dd28

**Comment by Misaki290** [comment]
> When there are more than 2 items in the list, you should add a comma after the penultimate item for clarity. E.g. tough, angry, or shielded
> 
> There was actually a court case that hinged on this serial, or so-called Oxford, comma. https://www.huffpost.com/entry/oxford-comma-court-case-ruling-overtime_n_58cad41ae4b0ec9d29d9dd28

That's really interesting. Well, we don't have that in the romanian grammar, I think.

**Pull request merged**
