### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by Lux-Sakura**
Clarifications up to line 1080~. Started back from the beginning to fix both trans and eng. More to come.

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
@DexterHuang

**Comment by Lux-Sakura** [comment]
Additional clarifications to the end of en.json.

**Comment by DexterHuang** [comment]
@Lux-Sakura  the english is in the code, so I have put the corrections to the code :D

**Comment by Lux-Sakura** [comment]
> 
> 
> @Lux-Sakura the english is in the code, so I have put the corrections to the code :D

Oh, I'll remember that next time! Sorry!

**Pull request merged**
