### PR TITLE
Update tips.txt

### PR DESCRIPTION
**Pull request by Lance0-32**
Added 11 new tips. I have now contributed 16 tips so far, oh yeah also I updated one tip due to the insanely low value of ECs

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
@Lance0-32 
(numbers mean lines i have questions about)
> 163 and 169
do not need to be changed
> 131
you dont need a full clear to have a quest spawned
> 147
tried refreshing? :)
> 154
?
> 155
what if i need help in dung Or i want to clear it with others
by the way, quick tip, you get tons of exp from mob kills in dung, so it's even better to share an uncleared dung link :)
> 153
gang crates can only be found in gang dung which requires being in gang 
> 180
can you edit that 4 enemies in a room is max?
@DexterHuang is 182 alright?

**Comment by Lance0-32** [comment]
163, fair, 169, I added it just because EC is free nowadays, but if people don't know that then yeah I guess that makes sense.

131 ok I got scammed by chat I thought the dungeon quest where you have to clear it needs to actually be cleared, not just rushed to the dungeon room.

147 I'm blind @.@ 

154 is on the rule of alts, basically don't create too many alts

155 ah I see, the way I phrased it made it look like you have to post only fully cleared ones. I meant that if you cleared a dungeon, you may as well post it in chat so everyone can benefit. I meant it as "If you have a fully cleared dungeon, send it in chat", not "If you send a dungeon, it must be fully cleared"

153 scavenging? Unless that also needs you to be in gang in which case oops I'll delete that

180 Eh, sure

182 is long lol, might have to delete that

**Comment by kt0t0Sudd3n** [comment]
skammed by chat xD. it's alright lol
about 154 
"creating only 1 acoount" might mislead people, mind changing it to "alt"?
change everything else  however you like

**Comment by Lance0-32** [comment]
closed because new ver

**Pull request closed without merging**
