### PR TITLE
guide

### PR DESCRIPTION
**Pull request by kt0t0Sudd3n**
guide how to create a pr on gh in updates log
@DexterHuang

### CODE REVIEW

**Comment by DexterHuang** [comment]
@kt0t0Sudd3n im not sure what u mean

**Comment by kt0t0Sudd3n** [comment]
@DexterHuang "If you would like to help to maintain CyberCode Online, please feel free to submit a PR at [our GitHub repo](https://github.com/DexterHuang/CyberCodeOnline)."
this is in this file
many people don't know how to make a pull request on GitHub so i added a guide how to do it

**Comment by DexterHuang** [comment]
ahh lmao i  see, my brainnnnn

**Comment by kt0t0Sudd3n** [comment]
haha Dex its fine
take a rest :)

**Pull request merged**
