### PR TITLE
Weekly Updates (RU) [25.01.2022]

### PR DESCRIPTION
**Pull request by Datarata**
# **Weekly Updates (RU) [25.01.2022]**
## Preface from the translator
_Hi! This is my first weekly update. Updates will be released on one of the last days of the week, but no later than 23:59 GMT on Sunday. Please send all errors, bugs, typos, either to me in a telegram, or to me by e-mail - art.ves.work@gmail.com._

_The entire translation is done by one person, but with the participation of others. If you also want to help translate into Russian, then write to me so that we can coordinate our actions and not interfere with each other._

_The translation was prepared by Avanpost [N_R]_

### ..\contribution\lang\ru.json

- Fixed machine translation.
- Changed "Dungeon" to "Metro"
- Minor fixes in the "Premium Store"
- Corrected the translation for "Subscriptions" (Donations)
- Replaced the fortress with a "data center", so it is more suitable for translation.
- I replaced "You" with "You", in Russian this word has two meanings, I replaced it with the correct one.
- Corrected the previous translation, with the removal of the number of participants in the pass, at the request of the players. (Returned numbers)
- Corrected errors in the past translation.

### ..\contribution\word-filter.json

- Added a few obscene and offensive words

### ..\credits.md

- Added myself to the translators
- Sorted everything alphabetically for beauty

### CODE REVIEW

**Comment by Datarata** [comment]
I'm sorry, cancel the edits to “words”, I mixed up the files -_-

**Comment by DexterHuang** [comment]
Hello :) I think we dont need to re-arrange the credit list,
also why are dungeon translated into "metro"? it seems to be like that from translator

**Comment by Datarata** [comment]
> Hello :) I think we dont need to re-arrange the credit list,
> 
> also why are dungeon translated into "metro"? it seems to be like that from translator

Hi, Dex :) 

The metro, since after consulting with the players, the metro was more suitable, since Shangri-La is the city of the future and the dungeons are more suitable for the "Middle Ages". Therefore, I changed it at the request of the ru community 😅☺️

**Comment by DexterHuang** [comment]
hmmmm I think it might create confusion when communicating, can we revert the change of "metro" and re-arrangement of credit? or simply create another PR, just copy the change you want to another PR

**Comment by Datarata** [comment]
> hmmmm I think it might create confusion when communicating, can we revert the change of "metro" and re-arrangement of credit? or simply create another PR, just copy the change you want to another PR

Okay, bro ^^

**Pull request closed without merging**
