### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by Gearbreaker-Vizu**

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
@Gearbreaker-Vizu made an oopsie... sorry
can you change "Kryndell Bot"? it has an actual nickname in it
(as i know there is none)

**Comment by Gearbreaker-Vizu** [comment]
Ah, I apologize, all right. I'll delete it for now since I can't think of other suitable nickname. Thanks for the revision ^^

**Comment by DexterHuang** [comment]
seems like the file isnt valid json @@

**Comment by Gearbreaker-Vizu** [comment]
> seems like the file isnt valid json @@

I don't understand why this happened. What should I do? Should I submit a new one?

**Comment by kt0t0Sudd3n** [comment]
> > seems like the file isnt valid json @@
> 
> I don't understand why this happened. What should I do? Should I submit a new one?

yes

**Comment by Gearbreaker-Vizu** [comment]
> > > seems like the file isnt valid json @@
> > 
> > 
> > I don't understand why this happened. What should I do? Should I submit a new one?
> 
> yes

OK then, thank you

**Pull request closed without merging**
