### PR TITLE
feat: provide Ukrainian translation for Donation

### PR DESCRIPTION
**Pull request by Kadzup**

### CODE REVIEW

**Comment by DexterHuang** [comment]
hello :D thanks for translating to Ukrainian, 
there was a update to this file before, could you align it to this one instead of the old one?
https://github.com/DexterHuang/CyberCodeOnline/blob/master/contribution/mobile/en/popup-tutorial/donation.md

**Comment by Kadzup** [comment]
> hello :D thanks for translating to Ukrainian, 
> there was a update to this file before, could you align it to this one instead of the old one?
> https://github.com/DexterHuang/CyberCodeOnline/blob/master/contribution/mobile/en/popup-tutorial/donation.md

Hi bud
Will check it in hour

**Comment by Kadzup** [comment]
@DexterHuang, fixed

**Comment by DexterHuang** [comment]
Thank you <3

**Pull request merged**
