### PR TITLE
Create 3HelixNetwork1.md

### PR DESCRIPTION
**Pull request by byakkozen**
gradual progress of Neon Circuit 's backstory. this is 2 of the three pieces (the 3helix Network represents tripplehelix's faction, which later joins the Trinity Alliance, later renamed (current time/present) to N30N_C1RCUS

### CODE REVIEW

**Comment by tripplehelix** [comment]
Why am I so excited about this? lol

One correction: 
```
Your media news outlets have been paid to deceive and lie to its citizens, intending
```

**Comment by DexterHuang** [comment]
very cool!

**Comment by DexterHuang** [comment]
you might have forgot to add this into index.json?

**Comment by tripplehelix** [comment]
Did you fix the spelling issue?

**Pull request merged**
