### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by EvJack**
I finished translating the ru.json file that the user Fremadico started

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
@tripplehelix is adding code lines fine?

**Comment by tripplehelix** [comment]
Please ask @DexterHuang about anything you want to add to the document. We need to make sure the file is parsed correctly.

**Comment by tripplehelix** [comment]
> @tripplehelix is adding code lines fine?

What was added?

**Comment by EvJack** [comment]
I added a translation of the description since it didn't exist

**Comment by tripplehelix** [comment]
@EvJack could you remove that addition and I'll merge this.

**Comment by EvJack** [comment]
@tripplehelix I can't delete this extension because it must have English text. I've fixed my mistake

**Comment by EvJack** [comment]
I saw your request about the names of the items. Give me time to return the items names to English

**Comment by EvJack** [comment]
@tripplehelix  I did as you asked

**Comment by tripplehelix** [comment]
<3

**Comment by tripplehelix** [comment]
@DexterHuang these descriptions should probably be added to the translation sheets.

**Pull request merged**
