### PR TITLE
N30N C1RCUS - Initial import

### PR DESCRIPTION
**Pull request by bvcxz-cybercode**
Adds the N30N C1RCUS lore from Discord.

### CODE REVIEW

**Comment by DexterHuang** [comment]
Hey its awesome and creative, but I think we need to split the lore into small bites, that is short enough to fit in phone screen is best

**Comment by bvcxz-cybercode** [comment]
Hmmm, that's going to be hard - maybe this stuff is best off in a wiki somewhere. I'll close this pull request and just keep it in my fork for now.

**Comment by DexterHuang** [comment]
It couldn't be just split the lore into different mds, like maybe each MD just one paragraph and we can have "1/5", you can see what Celesmeh pushed before, I think it has something similar

**Comment by bvcxz-cybercode** [comment]
Let me see what I can do .. mine are probably easy, and I'll see if _Worzel_ and _dec\_keeper_ are ok with me mangling their's.

**Comment by bvcxz-cybercode** [comment]
(going to delete this branch and start again)

**Pull request closed without merging**
