### PR TITLE
New translations added

### PR DESCRIPTION
**Pull request by makokii**

### CODE REVIEW

**Comment by tripplehelix** [comment]
@alfaice ;)

**Comment by alfaice** [comment]
@tripplehelix Looks good

**Comment by Misaki290** [comment]
Why people never say what translation is or what exactly they are changing in the files? 😒

**Comment by alfaice** [comment]
@Misaki290 Just check the Files changed tab

**Comment by Misaki290** [comment]
> @Misaki290 Just check the Files changed tab

I know, but it wouldn't be bad if people took an extra minute to detail what they were doing in the file.

**Comment by makokii** [comment]
> > @Misaki290 Just check the Files changed tab
> 
> I know, but it wouldn't be bad if people took an extra minute to detail what they were doing in the file.

Sorry, my bad. I'm pretty new to github, next time I will specify the lines I changed in the description :)

**Comment by tripplehelix** [comment]
We are happy for any effort you provide with your PR's @makokii thank you very much for taking the time with this one. <3

**Pull request merged**
