### PR TITLE
Update Credits.md

### PR DESCRIPTION
**Pull request by Misaki290**
- Removed social media links, only exception is SilverCrow's podcast link. Better to be safe than sorry.
- Corrected ArkyROU's name.
- Added WhirlingDervish as mod.
- Added myself at Proofreading.

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
links should be there as i know

**Comment by Misaki290** [comment]
> links should be there as i know

Doesn't have to.
At least not social media links.

**Comment by kt0t0Sudd3n** [comment]
@Misaki290 lemme find it, as i remember, either trip or Dex added their links

**Comment by Misaki290** [comment]
> UPD

I am supposed to know what's that?

**Comment by kt0t0Sudd3n** [comment]
> I am supposed to know what's that?
UPDate of comment

**Comment by Misaki290** [comment]
> > I am supposed to know what's that?
> > UPDate of comment

Just say 'Edit'. Stop complicating things further than it's necessary. 🙄

**Comment by kt0t0Sudd3n** [comment]
they did

**Comment by Misaki290** [comment]
IMG_20210523_160854

Press X to doubt.

**Comment by Misaki290** [comment]
> they did

They shouldn't have done that if they would care about their privacy. 🙄

**Comment by Misaki290** [comment]
@DexterHuang

**Comment by DexterHuang** [comment]
Social media ling is totally fine, it's to credit them, some people, like artists will not have github, basically add which every you want 😊

So please don't delete their links haha

**Comment by Misaki290** [comment]
Still don't think that it's okay but fine.
I'll close this.

**Pull request closed without merging**
