### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by Neshaiy**
Full game french translation

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
@Neshaiy cannot be merged 
words/sentences only in "trans" line should be translated

**Comment by kt0t0Sudd3n** [comment]
@nopeholmes

**Comment by nopeholmes** [comment]
> @nopeholmes 

I'm not French 😌, thanks for tagging me btw

**Comment by nopeholmes** [comment]
> > @nopeholmes 
> 
> I'm not French 😌, thanks for tagging me btw

I'll check it

**Comment by Neshaiy** [comment]
> @Neshaiy cannot be merged
> words/sentences only in "trans" line should be translated

However I only touched the line "Trans" I just looked and I did not modify any line "en" 🤔

**Comment by Neshaiy** [comment]
I will redo my translation being more careful no worries 😁

**Pull request closed without merging**
