### PR TITLE
Create EXP_MEMORY_20.md

### PR DESCRIPTION
**Pull request by pixeloney**

### CODE REVIEW

**Comment by DexterHuang** [comment]
Hello the EXP_MEMORY_20 does not exist, do you meean EXP_MEMORY?

**Comment by pixeloney** [comment]
Maybe I was mistaken then, but I did notice that experience memory items stack by level in the inventory, and this is the id I got out of the item url for this stack?

**Comment by DexterHuang** [comment]
@pixeloney  hmmmm oh i guess this is special case, didnt though of that, we cant make community lore for this @@

**Comment by DexterHuang** [comment]
Sorry XD

**Comment by pixeloney** [comment]
Waha ok no worries 😅

**Pull request closed without merging**
