### PR TITLE
Update structure-mask.json

### PR DESCRIPTION
**Pull request by GearlessJ03**
Use second commit 
Update structure-mask.json
Floor Layouts:
755 for unix permissions 
766 for unix permissions 
777 for full unix permissions 
.ini for configuration file 
.dll for dynamic library link 
力　ちから　chikara = Japanese for "power"

### CODE REVIEW

**Comment by DexterHuang** [comment]
hello there seems to be some formating error

**Comment by andycandy-de** [comment]
Found invalid dungeon rooms
{"type":"bossRooms","roomNumber":142,"lineNumber":10629,"message":"Not all free fields are connected!"}
# # # # # # #   # # # # # # # 
#                           # 
#   # # #   # # #   # # #   # 
#       #   #       #       # 
#       #   #       #       # 
#       #   #       #       # 
#       #   #       #       # 
        #   # # #   # # #     
#       #   #   #   #   #   # 
#       #   #   #   #   #   # 
#       #   #   #   #   #   # 
#       #   #   #   #   #   # 
#       #   # # #   # # #   # 
#                           # 
# # # # # # #   # # # # # # #

{"type":"bossRooms","roomNumber":145,"lineNumber":10686,"message":"Not all free fields are connected!"}
# # # # # # #   # # # # # # # 
#                           # 
#           #   #   #       # 
#           #   #   #       # 
#           #   #   #       # 
#           #   #   #       # 
#           #   #   #       # 
            #   #   #         
#           #   #   #       # 
#       # # #   #   #       # 
#       #   #   #   #       # 
#       #   #   #   #       # 
#   #   # # #   #   #       # 
#                           # 
# # # # # # #   # # # # # # #

These rooms are not valid. There are closed areas which are not reachable. Just open a wall to enter these areas.

You can validate the dungeon with the CCO Dungeon Editor (https://github.com/andycandy-de/CCO-Dungeon-Editor)
https://cco-dungeon-editor.netlify.app/?parse=7f7f40015ddd451145114511451105dc455545554555455545dd40017f7f
https://cco-dungeon-editor.netlify.app/?parse=7f7f40014151415141514151415101504151475145514551575140017f7f

**Comment by andycandy-de** [comment]
@Thugwife1111 You can change these rooms like my suggestions below:

"lineNumber":10629
https://cco-dungeon-editor.netlify.app/?parse=7f7f40015ddd45114511451145110554455545554555455545dd40017f7f
```
{
	"tiles": [
		"#", "#", "#", "#", "#", "#", "#", " ", "#", "#", "#", "#", "#", "#", "#",
		"#", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "#",
		"#", " ", "#", "#", "#", " ", "#", "#", "#", " ", "#", "#", "#", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", " ", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", " ", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", " ", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", " ", " ", "#", " ", " ", " ", "#",
		" ", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#", " ", " ",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", "#", "#", " ", "#", "#", "#", " ", "#",
		"#", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "#",
		"#", "#", "#", "#", "#", "#", "#", " ", "#", "#", "#", "#", "#", "#", "#"
	]
}
```

"lineNumber":10686
https://cco-dungeon-editor.netlify.app/?parse=7f7f40014151415141514151415101504151455145514551575140017f7f
```
{
	"tiles": [
		"#", "#", "#", "#", "#", "#", "#", " ", "#", "#", "#", "#", "#", "#", "#",
		"#", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "#",
		"#", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		" ", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", " ",
		"#", " ", " ", " ", " ", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", "#", " ", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", "#", " ", "#", "#", "#", " ", "#", " ", "#", " ", " ", " ", "#",
		"#", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "#",
		"#", "#", "#", "#", "#", "#", "#", " ", "#", "#", "#", "#", "#", "#", "#"
	]
}
```

Or you can remove these rooms. Otherwise the Pull request should be closed.

**Comment by DexterHuang** [comment]
there is still formating error, you can use json validation checker online, and there is conflicts with other people's merge too, I suggest you just copy and submit another PR

**Pull request closed without merging**
