### PR TITLE
Update it.json

### PR DESCRIPTION
**Pull request by Destro9000**
Added italian translation for some parts

### CODE REVIEW

**Comment by DexterHuang** [comment]
hey hello, there is some syntax error , I think you haven't pull from master for long time, the version your edit is based on seems to be very old :) try to do git pull

**Comment by Destro9000** [comment]
Do you mean the translated text?

**Comment by Destro9000** [comment]
So I can figure out and solve it

**Comment by Destro9000** [comment]
Strange , I pulled it out right this morning

**Comment by Destro9000** [comment]
I guess it is because I had to copy and paste from the downloaded and edited file I did and I had to remove and add parts to make it fit

**Comment by un-amico** [comment]
May I help with translation? (Posso aiutare con la traduzione?)

**Review by un-amico — COMMENTED** [review]
Perché è duplicato?

**Comment by Destro9000** [comment]
> Perché è duplicato?

Aspe , sto facendo un casino

**Comment by un-amico** [comment]
Vuoi una mano sulla traduzione?

**Comment by Destro9000** [comment]
> Vuoi una mano sulla traduzione?

Certamente , entra pure sul discord del gioco , MI trovi la

**Comment by Destro9000** [comment]
@DexterHuang can you try and see the last one I committed?
It should be this c9a492bbe30e0344710e7da187961af2a15f7d47

**Comment by tripplehelix** [comment]
How goes this? Is the last patch what you want to submit?

**Comment by Destro9000** [comment]
Yep this is the last I want to confirm

**Comment by DexterHuang** [comment]
hello the json has some syntax error @@, and it does look a bit strange, you seem to have a lot of duplicated thingy, click on "File Changed" to see what I mean

**Comment by Destro9000** [comment]
K I will edit the file again tomorrow

**Pull request closed without merging**
