### PR TITLE
Update and rename equiptment.md to equipment.md

### PR DESCRIPTION
**Pull request by Omnipotent-God**
Builds up mobile toturial starting from today. I see great potential in this game dont let me down. I like this game very much, this is my reason of putting time and effort refining his game.

### CODE REVIEW

**Review by tripplehelix — COMMENTED** [review]
Remove contribution at the bottom, this is all going in the update file now. Everyone is equal <3

Each main heading needs a '# ' before it. To fit with the theme of the other files.

**Comment by DexterHuang** [comment]
I think it's okay to put the name of contributors at bottom, the contribution should be recognized, that's the least I could do hahaha

As long as it is organized nicely it shouldn't cause problem

**Comment by tripplehelix** [comment]
> I think it's okay to put the name of contributors at bottom, the contribution should be recognized, that's the least I could do hahaha
> 
> As long as it is organized nicely it shouldn't cause problem

Alright, I can just see it becoming a mess. Maybe we can use God's implementation.

**Comment by Omnipotent-God** [comment]
done, added # in front of main headings

**Comment by DexterHuang** [comment]
https://stackedit.io
btw incase its the first time you use markdown, you can use an online editor like this one, would be easier to visualize

**Comment by Omnipotent-God** [comment]
> https://stackedit.io
> btw incase its the first time you use markdown, you can use an online editor like this one, would be easier to visualize

oooh yes this is exactly what i need

**Comment by tripplehelix** [comment]
The #'s need a space after them... easy to forget :D

**Comment by Omnipotent-God** [comment]
check it out now. should be fine

**Pull request merged**
