### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by Fremadico**
изменила названия редкостей, чтоб не конфликтовали с названиями предметов женского/среднего рода или множественного числа

### CODE REVIEW

**Comment by DexterHuang** [comment]
are you sure it is necessary to repeat "quality" in all quality names? in English we could just do say `rare sword`, not necessary to say `rare quality sword`

**Comment by Fremadico** [comment]
sadly, yes. otherwise there's a big grammar mistake. i thought about different solutions, but this seems to be the best one.

**Comment by kt0t0Sudd3n** [comment]
Adjectives in Russian are unfortunately not the same as in Eng and their form depends on Noun's sex and form
We are trying to find generic words so the rarity translation doesn't depend on equipment's form or we'll have to translate every equipment thingy with those adjectives manually

**Review by kt0t0Sudd3n — COMMENTED** [review]
@DexterHuang in case if we do the "quality" on each rarity we need it to be at the very of the equipment name
Example : Beret of Shielding низкого качества

**Pull request merged**
