### PR TITLE
Update ro.json

### PR DESCRIPTION
**Pull request by Misaki290**
Updated romanian translation.
Small corrections.
Added punctuations and capitalization.

### CODE REVIEW

**Comment by Misaki290** [comment]
I really don't know what the fk is wrong.
All I did was to literally copy paste what was in the en.json file.
It still gives me this stupid error "Process exited with error code 1".

**Comment by andycandy-de** [comment]
I corrected the json format

**Comment by Misaki290** [comment]
> I corrected the json format. You can see here what I changed -> [1e07eab?w=1](https://github.com/DexterHuang/CyberCodeOnline/commit/1e07eab42fa8bd4aa9cbfdf20a3f71dbd1863ed0?w=1)
> You just added an additional `}` above the `modal`

Thanks alot.

**Comment by kt0t0Sudd3n** [comment]
@Misaki290 thx
no need to translate anything in square brackets btw
if you translated them in the first place (job hub should be in like first 300 lines), program will duplicate translation of the text in square brackets so you dont need to translate them and save more time :)

**Comment by Misaki290** [comment]
> @Misaki290 thx
> no need to translate anything in square brackets btw
> if you translated them in the first place (job hub should be in like first 300 lines), program will duplicate translation of the text in square brackets so you dont need to translate them and save more time :)

Got it.

**Pull request merged**
