### PR TITLE
Update ContributeContent.json

### PR DESCRIPTION
**Pull request by Omnipotent-God**
new mob names added

### CODE REVIEW

**Comment by DexterHuang** [comment]
Lol I think one @Omnipotent-God is enough

**Comment by Omnipotent-God** [comment]
can i just keep one as mob names so it can be seen more often.

**Comment by tripplehelix** [comment]
I have to agree with Dex, adding players to the mob names just makes them less relatable to new users and only adds questions. Also you can't be a player and a mob!

**Comment by Omnipotent-God** [comment]
it here is not referring to me... it is referring to actually to a boss'es soldiers... i am trying to implement a powerful boss. you decide it is your game anyway. sry for wasting you guys' time

**Comment by DexterHuang** [comment]
One is okay haha

**Pull request merged**
