### PR TITLE
3 more tips added (attack, repair and storage limit)

### PR DESCRIPTION
**Pull request by Archibaald-dev**
I've added 3 more tips that i think are important, mostly for new players

### CODE REVIEW

**Comment by DexterHuang** [comment]
hey, you wanna add your name and link to the contributor list? :)

**Comment by Archibaald-dev** [comment]
Is that ok ? :)

**Comment by DexterHuang** [comment]
oh no no, dont add there, cuz this file will be read by the game programmatically, and no one looks here haha
add it at the top of update.md, that way ur name will show up every time there is update ;)

**Comment by Archibaald-dev** [comment]
sorry and thank you !

**Comment by DexterHuang** [comment]
:D

**Pull request merged**
