### PR TITLE
add some ukr words

### PR DESCRIPTION
**Pull request by Glitchavailable**

### CODE REVIEW

**Comment by Glitchavailable** [comment]
I dunno how to fix it. Sorry. I'm just translator😥

**Comment by Glitchavailable** [comment]
I dunno how to fix it. Sorry. I'm just translator😥

**Comment by Glitchavailable** [comment]
> I seems like there is error in the JSON format

I don't know how to fix it😥. I'm just translator

**Comment by Glitchavailable** [comment]
> > I seems like there is error in the JSON format
> 
> I don't know how to fix it😥. I'm just translator

Maybe thats because I wrote words with quotes and comman in ukr. May I try to do it with eng quotes?

**Comment by EgorSoppa132** [comment]
There is no coma on line 316

**Comment by EgorSoppa132** [comment]
There should be no coma on 355

**Pull request closed without merging**
