### PR TITLE
Rename kr.json to ko.json

### PR DESCRIPTION
**Pull request by Kraken-Juice**

### CODE REVIEW

**Comment by DexterHuang** [comment]
@Kraken-Juice  I think kr is the correct name for Korea

**Comment by tripplehelix** [comment]
> @Kraken-Juice I think kr is the correct name for Korea

We are having a problem finding a decicive answer. Some sites say it's KO-KR for korea and KO-KP for noth korea... Some just say it's KO for korea
I guess KO should be fine? @DexterHuang

**Comment by DexterHuang** [comment]
Let me double check again tomorrow @@

**Comment by tripplehelix** [comment]
Finally settled on KO

**Pull request merged**
