### PR TITLE
Update structure-mask.json

### PR DESCRIPTION
**Pull request by darkrevelations**
Added dungeon from Discored. 

Credit: SKIFFI

### CODE REVIEW

**Comment by darkrevelations** [comment]
Added SKIFFI to credits

**Comment by darkrevelations** [comment]
Added dungeons from Discord.

Credit: RezaRnew100

**Comment by darkrevelations** [comment]
Added dungeon from Discord.

Credit: RezaRnew100

**Comment by tripplehelix** [comment]
You've got a dungeon in here duplicated....

**Pull request merged**
