### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by Cyber-nun2**
Added 9 Tasks;
Added 2 bad guys;
Capitalize the remaining uncapitalized bad guys;
Added 8 good guys;
Deleted the second "nerk" (good guys) since it was already mentioned in the list.
Added 7 bosses;
Corrected "Gordon Ramsey" to "Gordon Ramsay" (bosses).
Added 1 greeting;
Capitalized almost all greetings;
Added 3 filler;
Added 2 needHelp;
Capitalize needHelp;
Corrected "Pbble-dashed" to "Pebble-dashed"(buildingPrefix) 
Added 4 helmets;
Corrected "Cemetary" to "Cemetery" (Building types)
Corrected "Carinval" to "Carnival" (Building types)
Added 3 buildings;
Added an accent to both capitalized and uncapitalized word of "café".
Added 2 upper armour.
Added 3 lower armour.
Corrected "underware" to "underwear" (lower armour);
Added 4 boots;
Corrected "havn't" to "haven't" (weaponSmith);
Corrected "It dangerous" to "It's dangerous" (weaponSmith).
Added 1 line to weaponSmith.
Added 1 line to bank NPC.
Corrected "pinterDefault" to "printerDefault".
Added 1 line to printer NPC.

### CODE REVIEW

**Comment by DexterHuang** [comment]
Hey @Cyber-nun2  thanks for the contribution, but some of the capitalization will actually mess up with the story generator, as some of the text will be used in mid sentence, so capitalize the text would cause some problem

**Comment by DexterHuang** [comment]
Oh it's merged 0.0

**Comment by tripplehelix** [comment]
Which were you referring to @DexterHuang ?

**Comment by tripplehelix** [comment]
Which sections should be uppercase and which should be lowercase? Obviously names and acronyms need to be capitalised.

**Pull request merged**
