### PR TITLE
Update procedural-names.json

### PR DESCRIPTION
**Pull request by Jognatan**
Upgrading names.

### CODE REVIEW

**Comment by Pr0dam** [comment]
Why do they need to be upgraded exactly?

**Comment by Jognatan** [comment]
> Why do they need to be upgraded exactly?

French culture

**Comment by Pr0dam** [comment]
Can you explain what that means? i see you have added (e) to the end I'm a little unfamiliar with that

**Comment by Jognatan** [comment]
This is for male and female words
________________________________

**Comment by Jognatan** [comment]
For exampel.
Pistolet brutal
Mitrailleuse brutale
________________________________

**Pull request merged**
