### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by darkrevelations**
Added a lot of new words and phrases.

### CODE REVIEW

**Comment by DexterHuang** [comment]
hey wild alot of the words are perfect but some of the words in there doesn't really fit the Cyberpunk theme, maybe we should remove those fantasy RPG things?@@

**Comment by darkrevelations** [comment]
Sure thing! I could also rename them and fit a more digital theme as well.

**Comment by darkrevelations** [comment]
Redacted some words that were more fantasy-based. Added some new words and phrases. Edited some words to make them fit the game style as well.

**Comment by darkrevelations** [comment]
Fixed a syntax error. Period instead of a comma lol. Typos get me sometimes.

**Comment by darkrevelations** [comment]
Added words from the discord channel. Pretty much cleared the queue.

**Comment by darkrevelations** [comment]
Added rooms, moved a "bossroom" to boss section. Was placed by error in normal rooms.

All discord channel contributions added from channel except level set. Requires Dex's attention.

**Comment by darkrevelations** [comment]
Updated wrong patch. Was grabbing updated file information and forgot to switch to master. Feel free to check it. No changes made.

**Comment by darkrevelations** [comment]
FoxHunt:

"Posted some new words for helmet on Github,

"ushanka",
"neko-earphone",
"straw hat",
"cyber oni helmet",
"space helmet",
"scuba diver helmet",
"Nijmegen helmet",
"Akoda-nari kabuto helmet",
"Eboshi kabuto helmet",
"Hockey helmet" "

---

NinkPT
Helmets:

" "Jack O'Lantern"
"Chullo"
"Gat"
"Jaapi"
"Crown" "

---

Hally:

"miscTask: munching on some chips, doing everything wrong
bosses: Kirbyroth, Little Nightmare
helmet: denim cap, santa hat, bandana
upperArmor: gardening smock, fishing vest, chesterfield coat, school blazer
lowerArmor: school pants, school skirt, biker shorts"

--

Redinator:

"upperArmor: Muumuu
boots: Slides, Flip-Flops"

---

Kaktusmonas in collaboration with Veyrin (me):

"Your Reflection"

---

Kaktusmonas:

"Headphones to helmet
Peg legs for either LowerA or Boots
Quote for Printer "Don't worry, we won't run out of ink." "

**Comment by darkrevelations** [comment]
Crediting users for creating words.

**Comment by tripplehelix** [comment]
OK all credits have been added to the credits.md file I'll check through what you've done here in a sec.

**Pull request merged**
