### PR TITLE
Proofreading Batch #1

### PR DESCRIPTION
**Pull request by epixinvites**
This is my first batch of edits.

### CODE REVIEW

**Comment by epixinvites** [comment]
I think I accidentally did something wrong... why is there so many commits that doesn't belong to me.

**Comment by epixinvites** [comment]
I think i messed something up

**Comment by darkrevelations** [comment]
What did I come back to?

**Comment by epixinvites** [comment]
ehhhhh well, its actually just 39 lines of changes @darkrevelations

**Comment by epixinvites** [comment]
i accidentally messed up and i reverted it, you can check the changes in the Files Changed tab

**Comment by tripplehelix** [comment]
I'm just going to ignore this and hope the notes and index file are all good.

**Pull request merged**
