### PR TITLE
Update word-filter.json

### PR DESCRIPTION
**Pull request by epixinvites**
Nerd is actually an actual word with no malicious meanings
> Nerd : a person devoted to intellectual, academic, or technical pursuits or interests

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
@DexterHuang

**Comment by DexterHuang** [comment]
well what do you guys think ?@@

**Comment by epixinvites** [comment]
I've given you the meaning for it, its nothing bad trust me.

**Comment by Lance0-32** [comment]
I think it's based on the delivery of the word. You'd have to try to be sarcastic (e.g. Yeah sure. Whatever, nerd) or just add words that could be filtered anyway (e.g. STFU nerd) for it to be bad. It alone with neither of those in an ok way (e.g lol I just said kryndellbot can detect niceness which is cool and he just nerded out on how he can do it using neural networks and stuff) is ok ig, and we always have 🤓 soo people gonna bypass it that way (e.g. 🤓 ---> (player's name)) so yeah. Don't think it would hurt tbh, it does harm to people sensitive but then again this is the internet, what did you expect.

**Pull request merged**
