### PR TITLE
Update procedural-names.json

### PR DESCRIPTION
**Pull request by Pr0dam**
Added some extra bosses and a pants prefix

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
please add commas
@Pr0dam

**Review by Pr0dam — COMMENTED** [review]
added the comma's

**Comment by Jeremy2801** [comment]
You've added a comma on the last entry of the list (line 1564) it seems. you need to delete it or the file will not be interpreted as "json".
In those type of file you have commas between each entries. So as there is no entry after the last one, you don't need a comma.
I'm french so sorry if my english is not perfect ;)

**Comment by DexterHuang** [comment]
https://jsonlint.com/
use this lol

**Review by Pr0dam — COMMENTED** [review]
fixed the errors now i hope

**Comment by Pr0dam** [comment]
whooo learning Github hahaha

**Review by Pr0dam — COMMENTED** [review]
forgot to add the prefix flamethrower to the other guns

**Comment by DexterHuang** [comment]
can we not add player names?

**Pull request merged**
