### PR TITLE
Update procedural-names.json

### PR DESCRIPTION
**Pull request by Slippzz**
Added:
Cyber Goths Cyber Locks (Helmet)
Cyber Ravers Tight Crop Top (Upper)
Cyber Ravers Vinyl Corset (Upper)
Cyber Goths Miniskirt (Lower)
Cyber Ravers Micro Miniskirt (Lower)
Cyber Ravers Furrie Booties (Boots)

### CODE REVIEW

**Comment by Slippzz** [comment]
I found it : )

**Comment by DexterHuang** [comment]
Hi you should put prefixes to common parts, the system will chose from there automatically

**Comment by Slippzz** [comment]
> Hi you should put prefixes to common parts, the system will chose from there automatically

**Comment by Slippzz** [comment]
Can you explain that a bit? Sounds like you want me to name them all common?

**Pull request closed without merging**
