### PR TITLE
office_worker_log_2

### PR DESCRIPTION
**Pull request by js147896325**
幹 我的雞塊

### CODE REVIEW

**Comment by kt0t0Sudd3n** [comment]
this has swears, right?

**Comment by js147896325** [comment]
> this has swears, right?
Well, if needed I can change it OHO

**Comment by js147896325** [comment]
If you get it, the swearing has nothing to do with insult any, it's just pure disappointment cause dude's chicken nuggets eating experience is gone. If dex disapprove this cause it contains swears in it, sure I might change it

**Comment by js147896325** [comment]
Just to make it clear that the least thing I want is this stupid story somehow get cancel, so I think this level of compromise seems reasonable to me. If it need to be change, I will change it

**Comment by kt0t0Sudd3n** [comment]
if @DexterHuang is ok with it, then cool

**Comment by DexterHuang** [comment]
let me change it, since it will be part of game UI its best not have it anyway

**Pull request merged**
