### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by darkrevelations**
Added some bad guys, good guys, and bosses.

### CODE REVIEW

**Comment by darkrevelations** [comment]
Fixed syntax errors with second commit push.

**Comment by darkrevelations** [comment]
Added a maze room to the maps.

**Comment by darkrevelations** [comment]
Added words from discord channel "words" to patch-5

**Comment by darkrevelations** [comment]
Accidental closure. Was renaming my patches since I deleted old ones from pull requests.

**Comment by darkrevelations** [comment]
Added some maps from the discord channel.

**Comment by darkrevelations** [comment]
Added "your reflection" to reflect request in Discord "Words" channel to add a boss named "You". Discussed with user to come up with a more viable name.

**Comment by darkrevelations** [comment]
Added more requested words and phrases. 1 helmet, 1 boots, 1 printer quote.

**Comment by tripplehelix** [comment]
@darkrevelations holy cow dude, you're a god send. Could you please react with the tick emoji to all the discord additions you've merged? Thanks!

**Comment by darkrevelations** [comment]
Absolutely!

**Pull request merged**
