### PR TITLE
Added Multiple Things

### PR DESCRIPTION
**Pull request by GooseGooseStop**
Added multiple dungeon layouts, a few tips, some not allowed words, a dungeon lore entry, and my name to the credits in the appropriate places.

### CODE REVIEW

**Review by GooseGooseStop — COMMENTED** [review]
fixed a closed off space in one of the dungeon layouts

**Comment by DexterHuang** [comment]
dungeon still broken@@

**Comment by GooseGooseStop** [comment]
> dungeon still broken@@

ya, I saw that.. the validation worked on the site in the README and I never touched the bossrooms, weird. Lemme look it over and see if I can't find what's causing it.

**Comment by GooseGooseStop** [comment]
completely forgot that when I first opened it I created a duplicate room as a template and later realized it was in the boss rooms but forgot I did that.. my bad, fixed now, though!

**Pull request merged**
