### PR TITLE
Lore changes 01

### PR DESCRIPTION
**Pull request by JustACloud**

### CODE REVIEW

**Comment by andycandy-de** [comment]
Work In Progress: This pull request isn't completed

**Comment by DexterHuang** [comment]
I would suggest creating the actuall notes before the index :)

**Comment by andycandy-de** [comment]
Or just create the pull request when all changes are done

**Review by JustACloud — COMMENTED** [review]
This should be good to go!

**Comment by andycandy-de** [comment]
Can someone check if this branch can be merged? Technically, everything is fine.
@DexterHuang can the game handle these <div> tags?

**Comment by DexterHuang** [comment]
@andycandy-de if i am not wrong, the div tag is there purely for decoration? make it looks like code?

**Comment by JustACloud** [comment]
I haven't ran across this in game to see if it can handle the <div> tag or not, though I was almost sure I'd seen centered text prior. My bad for not seeing this notification sooner.

**Comment by DexterHuang** [comment]
it shouldnt @@ dont use html tag, only use markdown :D

**Pull request merged**
