### PR TITLE
wootlespull2

### PR DESCRIPTION
**Pull request by Wootles**
Let's try this again. Corrected my rooms, added more stuff.

### CODE REVIEW

**Comment by DexterHuang** [comment]
Hi I have commented something there, it needs to use first person, because how it is used in the game@@ third person won't make sense

**Comment by Wootles** [comment]
If miscTasks is used for both the activity in line one and the activity in line three, then isn't it in third person the first time and first person the second time?  If so it's a problem if we use any sort of reference isn't it?

image

**Comment by Wootles** [comment]
....perhaps the answer is just to use indefinite articles like

updating an OS

and just rewrite them entirely

**Comment by DexterHuang** [comment]
@Wootles oh you are right, actually there should not be any person, unless its named person like "I was kissing 'Obama'", no 'my/them/his/you'

**Comment by Wootles** [comment]
Yeah, I can take that task.  

Would you be okay with pulling this (if there's no other problems) and I can commit a rework of it on my next pass?

**Comment by DexterHuang** [comment]
done :D

**Pull request merged**
