### PR TITLE
Added to words.json

### PR DESCRIPTION
**Pull request by IIJJ22GG**
Just added some stuff I thought of

### CODE REVIEW

**Comment by IIJJ22GG** [comment]
Weird, why did Github decide to use a random branch instead of master

**Comment by DexterHuang** [comment]
@IIJJ22GG  because it needs approval before its merged to master :) incase there are some issues, which there seems to be haha
seems like there are some invalid JSON problem :) could you check?

**Comment by Ezo** [comment]
Its just a missing comma on line 1123 (after "*grunts*")

**Comment by IIJJ22GG** [comment]
Oops, I missed a comma. Fixed.

**Pull request merged**
