### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by darkrevelations**
Many words and phrases added. Some capitalization here and there. Mostly words though.

### CODE REVIEW

**Comment by DexterHuang** [comment]
Oh no.. Please don't capitalize them, it would break the system haha

**Comment by darkrevelations** [comment]
Will fix it here in a sec

**Comment by darkrevelations** [comment]
Running draft checks on the json syntax right now

**Comment by darkrevelations** [comment]
@DexterHuang does everything need to be lowercase or just the things I changed?

**Comment by DexterHuang** [comment]
Just the thing you changed is fine 🙂

**Comment by tripplehelix** [comment]
Keep capitalisation as it was in the rest of each list. I know one of the lists is a mess of both, but I've never had a clear answer from @DexterHuang on that one.

**Pull request closed without merging**
