### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by Kamtoru**
Translation update

### CODE REVIEW

**Comment by DexterHuang** [comment]
hello there seems to be some syntax error

**Comment by DexterHuang** [comment]
hello there seems to be some error

**Comment by Kamtoru** [comment]
And now?

**Comment by Kamtoru** [comment]
Аnd tell me if it is possible to change the font for translation? The current font is uncomfortable and ruins the gaming experience

**Comment by DexterHuang** [comment]
> Аnd tell me if it is possible to change the font for translation? The current font is uncomfortable and ruins the gaming experience

can you show me how it shows up on your device?

**Comment by Kamtoru** [comment]
chrome_IVpcxOXNwh
1Q3JsLsp7D
chrome_otEdSim4Ov
chrome_7DSZCwfGPA

**Comment by DexterHuang** [comment]
whats the font thats commonly installed on Russian PC? do you know how to change font with inspect element? if so could you try to see if Arial looks fine?

**Comment by Kamtoru** [comment]
> какой шрифт обычно устанавливается на русский ПК? Вы знаете, как изменить шрифт с помощью элемента проверки? если да, не могли бы вы попробовать посмотреть, хорошо ли выглядит Arial?

the anrial fits perfectly

**Comment by DexterHuang** [comment]
okay i will try to make it show arial for russia in the next patch :)

**Pull request merged**
