### PR TITLE
Update ko.json and added more translation

### PR DESCRIPTION
**Pull request by 5h4ngho**
[smooth translation]
- ko.json (added more npc line too)
- procedural-names.json

[add more translation]
- global_skip.md
- popup-tutorial

[To translate later, simply copy the contents of the `en` folder]
- dungeon-lore
- item
- scenario

### CODE REVIEW

**Comment by 5h4ngho** [comment]
Dear Dex
Would it be okay to translate this items for that can explain to other contributors who same language?
If can, I'll translate it next PR.

item/lore.json
└"REMINDER" : ["The ${itemName} already ..."]

procedural-names.json
└"~~~~~_INSTRUCTIONS" : "Requires minimum...",

**Comment by ManzTellen** [comment]
As a fellow translator, feel free to translate those as well! That's basically a note for other contributors & it'll not affect / showing up in-game :)

**Comment by DexterHuang** [comment]
@5h4ngho  yes those thing does affact the game at all, so do translate or even add notes yourself :)

**Comment by DexterHuang** [comment]
Also I noticed you added english dungeon lores, dont add the english ones :) just add those you have translated or have added 
do know you are welcome to add notes that is only in Korean, it does not have to be in sync

**Comment by DexterHuang** [comment]
coul you remove the dungeon lore thats still in English ?@@

**Comment by 5h4ngho** [comment]
Oh man, I'm sorry.
I just did it because I was annoyed to copy the folder later😅
Removed lore-related contents that only copied the en folder from PR.
Next time, I'll translate it into Korean and commit.
sorry to bother.

**Pull request merged**
