### PR TITLE
Update words.json

### PR DESCRIPTION
**Pull request by Luako**
Added Another set of Baddies, will add more when I think of more.

### CODE REVIEW

**Comment by byakkozen** [comment]
I incorporated all of Luako's line into my patch/ fork at the time of this comment as I was working on testing alphabetizing the badguy list.

**Comment by Luako** [comment]
Cool cool man I’ve seen thanks, there was 18 though not 2? 😉 👍 looking forward to checking through, will be easier with alphabet to see duplicates and add more character names 👌

**Comment by byakkozen** [comment]
its all there I promise you 
"Brawler" - Line 172
"Body Morpher" - Line 170
the clown members - Line 176- 179
corrupted detective/ cyborg- Line 180/181
cyber pirate - line 191
enhanced replicant- line 202
gene-spliced mutant- line 252
insane surgeon- line 269
masked thug- 298
sadistic sociopath/ sophisticated psychopath- line 372/384
underground league fighter- line 414

**Comment by byakkozen** [comment]
Violent stalker- line 442

**Comment by Luako** [comment]
Nooo, sorry I was making a joke on your patch when you meant to write about 20 but it was wrote as 2?, I’ve seen they’re all there thanks :) you’ve done an awesome job 👌

**Pull request merged**
