### PR TITLE
proofreading and translation

### PR DESCRIPTION
**Pull request by Jhown-glitch**
Revision of **'tips.txt'**; added new translations to weapon names in **'procedural-names'**.

### CODE REVIEW

**Comment by Jhown-glitch** [comment]
About package-lock, I have no idea what those changes are. When I committed to my fork it showed up in the changes and I don't know how to stop it from going along with my PR translations.

**Comment by DexterHuang** [comment]
I think you will need to omit the change from package-lock.json also, some of the value you changed has space in front, it seems

**Comment by Jhown-glitch** [comment]
> I think you will need to omit the change from package-lock.json also, some of the value you changed has space in front, it seems

how can I do that? thought about deleting the file but the commit would come to my PR

**Comment by DexterHuang** [comment]
hmmm I think if its all abit confusing for you, you can simply copy your changes and make another PR?

**Comment by Jhown-glitch** [comment]
> hmmm I think if its all abit confusing for you, you can simply copy your changes and make another PR?

I can copy, but I can't paste it into a new PR, when creating a new PR it takes all the changes

**Comment by Jhown-glitch** [comment]
If I copy your original file and edit that package-lock, so adding again all the information that was mistakenly deleted; can you merge?

**Comment by Jhown-glitch** [comment]
That's it, I managed to revert the unwanted change by copying its package-lock and pasting it into the one in my fork :) I should have thought of that earlier

**Comment by DexterHuang** [comment]
looks great :) thanks

**Pull request merged**
