### PR TITLE
fixed some translation & few items name tweaking for indonesian language

### PR DESCRIPTION
**Pull request by crov-cco**
fixed some translation error, add some translation, and changed some items name so they sort better

### CODE REVIEW

**Comment by DexterHuang** [comment]
are you sure its good to add [] with short terms for names? maybe lets not do that and if the community wants it we can add it

**Comment by crov-cco** [comment]
It might be a bit long of explanation, so please bear with me

1. For the short terms of names on med items, it was inspired by how french translation simply named their meds like **"high-quality nano medic bot"** to **"Bot médical T5"**, but with some changes,

- And it's name abbreviation are pretty straightforward, for example **"ST1"** means **"Solo/Satu/Sendiri Tingkat 1"** in indonesian or **"Solo/Single/Self Tier 1"** in english (in case they're pretty used to english naming sense which commonly used/being left in on a lot of games even after translated to our language),
- and for **"TT1"** it's **"Tim/Teman Tingkat 1"** or **"Team Tier 1"**, could change this from "T" (Tim) to "G" (Grup) but the sorting system will end up putting these before the single person type meds (not a huge deal if they don't have any in inventory, but will be one once the name changes applied to crafting list names too)
- so it makes it quicker to know which meds are which without reading the whole name.


2. For the **"[ ]"** that are used on items "tier" should be fine to be removed since it's mostly just to make it easier to spot,
> But it's a little complicated on those that are used on items group/type mainly because of the translation of said group/type itself making it impossible to put in a way that are makes sense without messing with the sorting system (which ruin the reasons of the renaming itself, which is to make them sorted better)

- for example **"ElectroFiber Bites"** the translation are **"Serat Elektro Gigitan"**, i change it to **"Peliharaan [Makanan] Serat Elektro Gigitan"** which means **"Pets [Food] ElectroFiber Bites"** EN version, in english case its fine to remove the "[ ]" become **"Pets Food - ElectroFiber Bites"** and it'll still get them sorted nicely with other pet related items, but in our language it'll get translated to **"Makanan Peliharaan - Serat Elektro Gigitan"** and if i follow the same rule to all other items it'll be no different with it's current state and are spread all over the inventory because of the sorting system, thats why i put them in "[ ]".


>So that's it, sorry for it end up very long, but i believe i've delivered all the reasons for the changes, thanks for the attention

**Comment by DexterHuang** [comment]
yes I understand what it is meant for, I just worry it would confuse new players instead of helping them @@ people will ask what this and that means, and become confusing, do you mind just change the regular text thing and we can discuss with the community about modifying the item name?

**Comment by crov-cco** [comment]
alright

**Pull request merged**
