### PR TITLE
ro translation

### PR DESCRIPTION
**Pull request by Misaki290**
Continuation of the romanian translation.
(after 2 or 3 months or so)

### CODE REVIEW

**Comment by Misaki290** [comment]
It says that there's a conflic with the main branch.
I fail to see what's wrong with my translation patch.

**Comment by DexterHuang** [comment]
conflict doesnt mean there is something wrong, it means there was an edit before you committed your edit, and its asking which one you want to keep

**Comment by DexterHuang** [comment]
you do have a small mistake tho,
you can use https://jsonlint.com/
to validate and find where you have typo

**Comment by Misaki290** [comment]
> you do have a small mistake tho,
> you can use https://jsonlint.com/
> to validate and find where you have typo

Thanks for the tip.

**Pull request merged**
