### PR TITLE
New italian translations + improved procedural names translation

### PR DESCRIPTION
**Pull request by NaturallyCreepy**

### CODE REVIEW

**Comment by DexterHuang** [comment]
why do you add `/a` in many names?

**Comment by NaturallyCreepy** [comment]
@DexterHuang you can merge if you want, as I said on discord in the "Translations" channel the procedural names are ready to be translated 😉

**Comment by NaturallyCreepy** [comment]
> why do you add `/a` in many names?
It's for adjectives that have a different translation for female (end in "a") and male (end in "o"). Since I can't know beforehand if they refer to a male or female word, I made them a bit more general ending in "o/a" (or "i/e" if plural)

**Comment by NaturallyCreepy** [comment]
Added new translations on top of the old ones

**Comment by DexterHuang** [comment]
is the /a thing a part of your lanague? like you put that behind people's name? 🤔

**Comment by NaturallyCreepy** [comment]
> is the /a thing a part of your lanague? like you put that behind people's name? 🤔

I'll make an example to make it more clear:

Let's say we have two places, a house (italian: casa [female word]) and a castle (italian: castello [male word]).
In english, If I describe those places as "abandoned", I use the same adjective for both (abandoned house, abandoned castle).
In italian, I refer to an abandoned house with "casa abbandonat**a**", and to an abandoned castle with "castello abbandonat**o**".
And that is because casa it a female word, so the ending of the adjective ends with "a", and castle is a male word, so it ends with "o".

In this case, since I don't know in advance the name of the place that will be used along with an adjective, I must include both cases in a single word, that is "abbandonato/a". It's a common thing to do in italian for people name's when you don't know the gender of the subject.
Going back to our example, if I were to use just "abbandonato", then abandoned house would be translated as "casa abbandonato", which is not acceptable in italian.

I hope it makes sense :)

**Comment by DexterHuang** [comment]
I see, so it is normal for people to see "xxxx/a" or "xxxx/o" as someone's name for intalian language ya?

also there seems to be some conflict

**Comment by NaturallyCreepy** [comment]
> I see, so it is normal for people to see "xxxx/a" or "xxxx/o" as someone's name for intalian language ya?
> 
> also there seems to be some conflict

I made a mistake, it's used for adjectives related to people's names whose gender is unknown.

Regarding the conflicts, as I said in the comment section of your latest commit, it appears the conflicting parts where removed in the latest version of the file , hence why they are marked as conflicts.

**Comment by NaturallyCreepy** [comment]
Ok conflicts solved, but I had to remove the following strings:

> "eng": "Seems like there is a same status effect deployed by other player already. you may deploy again in ${time} minute."

> "eng": "Encountered an server side error, if you see this message, please wait for 2 minutes before making any other action to ensure it will not keep happening."

The other strings were moved as you said, but these aren't present anymore.

**Comment by NaturallyCreepy** [comment]
I think the PR can be merged now @DexterHuang

**Pull request merged**
