### PR TITLE
Fixed typos, grammar, organization (tips, tutorial)

### PR DESCRIPTION
**Pull request by Laani**
Organized tips for both desktop and mobile into sections for easier edits. Fixed typos and grammar issues in EN translation and tips.

### CODE REVIEW

**Comment by DexterHuang** [comment]
did you remove any tips?@@

**Comment by DexterHuang** [comment]
oh no there is conflict

**Comment by Laani** [comment]
> 
> 
> did you remove any tips?@@

Hi Dexter! I wanted to organize both web & mobile tips so they were in the same order and generally categorized so it's easier for future tips to be added without people needing to search through the entire list to see if a similar tip was created already.

For the most part I was just fixing grammar issues as I moved things around the doc without trying to add/remove any tips.

I forgot to mention I did delete a few from the web tips that didn't fit there - for example, "If you are reading this while driving, PUT THE PHONE DOWN!" probably doesn't need to show up in the web app.

**Comment by DexterHuang** [comment]
`I forgot to mention I did delete a few from the web tips that didn't fit there - for example, "If you are reading this while driving, PUT THE PHONE DOWN!" probably doesn't need to show up in the web app.`
yeah I agree

btw there are conflicts @@ its needs to be solved before merge

**Comment by Laani** [comment]
> yeah I agree
> 
> btw there are conflicts @@ its needs to be solved before merge

Fixed! 💗

**Comment by Laani** [comment]
Just fixed additional conflicts since the same files were edited by future pull requests.
Is there anything else I need to do before it's merged? I'm having to repeat some of the edits over and over. 😥

**Comment by Misaki290** [comment]
IMG_20210515_114557
IMG_20210515_114515

I'm pretty sure that I can carry in dungeons as much Energy Cells and Anti-matter charge as one stack allows me, which is 2000, not 1000.

**Comment by Laani** [comment]
@Misaki290 Thank you for catching that! That does sound way more correct haha. I copied the text over directly from the Equipment Tutorial, so I imagine that's just outdated information.

**Comment by Misaki290** [comment]
> @Misaki290 Thank you for catching that! That does sound way more correct haha. I copied the text over directly from the Equipment Tutorial, so I imagine that's just outdated information.

You take your information from the game.
Like you said, some information might be outdated, incomplete or even missing and nobody notice it.
Tutorial isn't updated as fast as the game is.

**Pull request merged**
