### PR TITLE
Missed some details

### PR DESCRIPTION
**Pull request by Omnipotent-God**

### CODE REVIEW

**Comment by DexterHuang** [comment]
hey maybe we create a new file for key fragment and keys, like progression stuff
since the key or fragment isn't really equipment :)

**Comment by Omnipotent-God** [comment]
yes that will be good

**Comment by Omnipotent-God** [comment]
let me delete stuff related to keys

**Comment by Omnipotent-God** [comment]
done, info about keys and frags removed from this page

**Comment by DexterHuang** [comment]
Actually, should we also have a AFK tasks file to explain the AFK mechanics and the item required instead of having the ai core and stuff in 'equipemnt' section, since they are not really equipment technically ?

**Comment by Omnipotent-God** [comment]
> Actually, should we also have a AFK tasks file to explain the AFK mechanics and the item required instead of having the ai core and stuff in 'equipemnt' section, since they are not really equipment technically ?

yeah sure

**Pull request closed without merging**
