### PR TITLE
Updated translation for Mandarin Tradtional

### PR DESCRIPTION
**Pull request by Chkj000**
Edit some translation

### CODE REVIEW

**Comment by Chkj000** [comment]
Thank you for looking my change.

**Comment by Chkj000** [comment]
Am I be able to be in the list of translator to keep helping improve this game?

**Comment by Chkj000** [comment]
Can I be a part of the translator group in the list? I have multi-background about translating languages to make the content better.

**Comment by DexterHuang** [comment]
hey hello, seems like there is a kind big conflict @@ could you resubmit again?

**Pull request closed without merging**
