### PR TITLE
Adding a new helmet and boss

### PR DESCRIPTION
**Pull request by Medve01**

### CODE REVIEW

**Comment by DexterHuang** [comment]
@Medve01  haha is facepalm a head wear?

**Comment by DexterHuang** [comment]
@kt0t0Sudd3n what u think?

**Comment by Medve01** [comment]
Yep :) and I'm not gonna stop playing, until I find an epic facepalm.

**Comment by kt0t0Sudd3n** [comment]
LMAO 
@DexterHuang i think its definetely not a helmet, but a funny addition

**Pull request merged**
