### PR TITLE
Update ContributeContent.json

### PR DESCRIPTION
**Pull request by mxjoda**
added several items, made a few things into sets (ie "royal divine robe" now has pants, "hacked cybernetic legs" now has arms and feet)

### CODE REVIEW

**Comment by DexterHuang** [comment]
hey thanks for the PR, I think it would be better we move those "criminal mastermind" etc to bad guy list instead of good guy?

**Comment by mxjoda** [comment]
> hey thanks for the PR, I think it would be better we move those "criminal mastermind" etc to bad guy list instead of good guy?

oshit yeah, that was a mistake sorry about that

**Comment by DexterHuang** [comment]
haha no worries, just let me know when you updated the branch :)

**Comment by mxjoda** [comment]
criminal mastermind was already under bosses, did you want me to move it to bad guys instead?

**Pull request merged**
