### PR TITLE
Corrección de errores y mejoras en la traducción

### PR DESCRIPTION
**Pull request by Elrecoal-19**
As the title says, I corrected many errors I found in the translation as well as I improved some parts of the translation to make it more homogeneous.

### CODE REVIEW

**Comment by Elrecoal-19** [comment]
Worth mentioning that I'm still getting used to Github, in case its strange all the extra things I did with the Pull Request

**Comment by kroliklapine** [comment]
hi! someone submitted an es translation right after you that got approved, so i am going to close this one, as very similar changes have already been made :)

**Comment by Elrecoal-19** [comment]
Okay, thanks for letting me know that people have already corrected it :)

**Comment by Elrecoal-19** [comment]
> hi! someone submitted an es translation right after you that got approved, so i am going to close this one, as very similar changes have already been made :)

Okay, thanks for letting me know that people have already corrected it :)

**Pull request closed without merging**
